---
title: "Who I am"
description: |
  My Interests and Experience
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Interests 

My entire academic and professional career has revolved around water resources. It began during my sophomore year at UC Santa Barbara, when I was in the early stages of pursuing an Environmental Sciences degree and California was in its second straight year of extreme drought. Having been born and raised in Chicago, Illinois, it was eye-opening to experience such great drought for the first time. It was around this time that a classmate told me about another degree program within the Environmental Studies department that focused specifically on the study of water. I thought that was a perfect opportunity to focus my education on a meaningful, ever-present issue that California, the American West, and much of the world face. That day, I switched to the Hydrological Sciences and Policy major and started on my career path in the world of water resources.

Seven years later, I remain on that path as a Master's degree candidate specializing in Water Resources Management at the Bren School of Environmental Science & Management. It is at the Bren School that I have been able to expand upon the foundation of knowledge from my undergraduate education in hydrology. While learning more about the policy and management side of water resources, I have been able to hone my interests onto what I find to be the most interesting and relevant topics related to water. Specifically, I have grown particularly interested in groundwater management and water markets, and the potential intertwining of those two topics. I am also interested in watershed-scale management, as it encompasses many of the water resources concepts I have learned throughout my education and career. Ultimately, my goal is to become one of the future leaders in water resources management, helping to improve the water availability, quality, and affordability for human and environmental uses in California and beyond.

## Experience and Projects

### Pre-Bren

After earning my undergraduate degree in Hydrological Sciences, I spent 3 years working for an environmental consulting company in Santa Barbara called Blue Tomorrow, LLC. I worked on a variety of projects there, including stream condition surveying, stormwater sampling, and some air quality monitoring. My primary project was stream condition surveying, which I performed over 2 years. For that project, I would backpack out to remote field sites in the backcountry of the Los Padres National Forest and camp there each week with a crew of myself and 3 others. Our team was tasked with surveying extended reaches of streams that are believed to be the last critical over-summering habitat for endangered Steelhead trout. Surveys included collecting physical, chemical, and biological data, which I would later manage and organize into comprehensive reports for clients.

### At the Bren School

While working towards my Master's degree in Water Resources Management, I have had the opportunity to work on exciting projects through a summer internship at the Public Policy Institute of California's Water Policy Center and through Master's Group Project work. For my summer internship at PPIC, I contributed research in one of the fields I am most interested in - Sustainable Groundwater Management. My project specifically looked at how the implementation of the Sustainable Groundwater Management Act (SGMA) would affect agricultural water users in the Sacramento Valley. I spent the summer compiling a dataset of surface water availability per irrigated acre for every agricultural water user in the Sacramento Valley. Understanding the landscape of which users have surface water and which don't helps understand which users will be impacted the most by the expected reductions in groundwater use mandated by SGMA. I created a spatial representation of my surface water avaialbility dataset and presented my findings to PPIC staff from all departments.

For my Master's Group Project, which works with clients at the California Department of Water Resources (DWR) and the Environmental Defense Fund (EDF), I have focused more on the supply augmentation side of groundwater management. My project, called Flood Forward, seeks to understand the potential for floodplain restoration to be used for managed aquifer recharge with the co-benefits of flood risk reduction and ecosystem enhancement. Our group is analyzing priority areas for flood risk and riparin ecosystem restoration throughout the Madera and Chowchilla groundwater subbasins in Madera County, California. We will ultimately produce a spatial output showing priority floodplains for siting groundwater recharge projects which can achieve the benefits of flood risk reduction and/or ecosystem enhancement.