---
name: Alex
surname: Ehrens
position: "Master's Candidate"
address: "Bren School of Environmental Science & Management"
phone: (224) 612-1637
email: "alexehrens@ucsb.edu"
linkedin: "https://www.linkedin.com/in/alexehrens/"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "Expected June 2021", "Bren School of Environmental Science & Management - University of California, Santa Barbara", "Santa Barbara, CA",
  "Bachelor of Science in Hydrological Sciences", "2016", "College of Letters and Science - University of California, Santa Barbara (UCSB)", "Santa Barbara, CA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Master's Group Project

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

